####################################################################################################
# Module manifest for module 'DevPack'
#
# Generated by: Todd Howard
#
# Generated on: 2012-24-05
#
####################################################################################################

@{
	# Script module or binary module file associated with this manifest
	ModuleToProcess = 'DevPack.psm1'

	# Version number of this module.
	ModuleVersion = '1.0'

	# ID used to uniquely identify this module
	GUID = '2d7901b6-3b88-4717-a1e5-b345e61fc255'

	# Author of this module
	Author = 'Todd Howard'

	# Company or vendor of this module
	CompanyName = 'Total180 Global'

	# Copyright statement for this module
	Copyright = '(c) 2012-2015 Total180 Global - All rights reserved.'

	# Description of the functionality provided by this module
	Description = 'PowerShell tools for developing with Git and Visual Studio'

	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = '4.0'

	# Name of the Windows PowerShell host required by this module
	# PowerShellHostName = ''

	# Minimum version of the Windows PowerShell host required by this module
	# PowerShellHostVersion = ''

	# Minimum version of the .NET Framework required by this module
	# DotNetFrameworkVersion = ''

	# Minimum version of the common language runtime (CLR) required by this module
	# CLRVersion = '2.0'

	# Processor architecture (None, X86, Amd64, IA64) required by this module
	# ProcessorArchitecture = ''

	# Modules that must be imported into the global environment prior to importing this module
	# RequiredModules = @()

	# Assemblies that must be loaded prior to importing this module
	# RequiredAssemblies = @()

	# Script files (.ps1) that are run in the caller's environment prior to importing this module
	# ScriptsToProcess = @()

	# Type files (.ps1xml) to be loaded when importing this module
	# TypesToProcess = @()

	# Format files (.ps1xml) to be loaded when importing this module
	# FormatsToProcess = @()

	# Modules to import as nested modules of the module specified in ModuleToProcess
	# NestedModules = @()

	# Functions to export from this module
	FunctionsToExport = '*'

	# Cmdlets to export from this module
	CmdletsToExport = '*'

	# Variables to export from this module
	# VariablesToExport = '*'

	# Aliases to export from this module
	AliasesToExport = '*'

	# List of all modules packaged with this module
	# ModuleList = @()

	# List of all files packaged with this module
	FileList = @(
		'DevPack.psd1',
		'DevPack.psm1'
	)

	# Private data to pass to the module specified in ModuleToProcess
	# PrivateData = ''

}

